<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagrams" nsURI="http://diagrams.ecore" nsPrefix="diagrams">
  <eClassifiers xsi:type="ecore:EClass" name="Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//NamedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NE_ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fragment" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//NamedElementTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//NamedElementTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altername" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignKey" upperBound="-1"
        eType="#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKey" lowerBound="1"
        eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//NamedElementSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Class" eOpposite="#//Class/references"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//NamedElementSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" eOpposite="#//Reference/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//NamedElementSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//NamedElementSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="STRING"/>
    <eLiterals name="INT" value="1"/>
    <eLiterals name="BOOL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentSource" eSuperTypes="#//Fragment #//NamedElementSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceReferences" upperBound="-1"
        eType="#//NamedElementSource" eOpposite="#//NamedElementSource/fragments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//Trace" eOpposite="#//Trace/sourceFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElementTarget" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="#//FragmentTarget" eOpposite="#//FragmentTarget/targetReferences"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElementSource" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="#//FragmentSource" eOpposite="#//FragmentSource/sourceReferences"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentTarget" eSuperTypes="#//Fragment #//NamedElementTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetReferences" upperBound="-1"
        eType="#//NamedElementTarget" eOpposite="#//NamedElementTarget/fragments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//Trace" eOpposite="#//Trace/targetFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFragment" eType="#//FragmentTarget"
        eOpposite="#//FragmentTarget/traces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFragment" eType="#//FragmentSource"
        eOpposite="#//FragmentSource/traces"/>
  </eClassifiers>
</ecore:EPackage>
